### ISSUE TITLE
[Discussion] Support for http / https basepaths

### ISSUE THREAD

**Issue by silvanheller** [lucaro/DRES#65]
The current assumption is that the whole collection is present on the same server as DRES.
While this is not a severe constraint, it might be desirable to support other basepaths for dev and testing purposes.

**Comment by lucaro** [comment]
DRES does serve all content itself, so I don't quite understand the issue, could you elaborate?

**Comment by silvanheller** [comment]
This would only be a backend change - for example, the FFmpegUtil class considers the collectionBasePath as a filepath

**Comment by lucaro** [comment]
The FFmpegUtil needs random access to the individual files in order to efficiently generate the various previews. While it would be possible to access them also via HTTP, it would be rather inefficient and result in longer loading times and a higher risk of request timeouts. I'd be hesitant to support this. It should be much more efficient to mount the collection into the filesystem through a network share, if it is not possible to have a local copy. Is there any particular use case where a collection can _only_ be accessed via HTTP?

**Comment by silvanheller** [comment]
No, I think for all use cases i can think of there are workarounds. It was more a question of convenience but i guess then we can close this as wontfix
